config/routes.rb
Rails.application.routes.draw do

  get "beans/current", to: "beans#current", as: :current_beans
  get "beans/cupping", to: "beans#cupping", as: :cupping_beans
  post "beans/:bean_id/rate", to: "beans#rate", as: :rate_bean
  post "beans/:bean_id/toggle_in_stock", to: "beans#toggle_in_stock", as: :bean_toggle_in_stock

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :beans
  resources :roasters
  resources :roast_levels
  resources :origins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "beans#current"

end

app/models/roaster.rb
class Roaster < ApplicationRecord
end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  before_action :set_roaster, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update]

  # GET /roasters
  # GET /roasters.json
  def index
    @roasters = Roaster.all
  end

  # GET /roasters/1
  # GET /roasters/1.json
  def show
  end

  # GET /roasters/new
  def new
    @roaster = Roaster.new
  end

  # GET /roasters/1/edit
  def edit
  end

  # POST /roasters
  # POST /roasters.json
  def create
    @roaster = Roaster.new(roaster_params)

    respond_to do |format|
      if @roaster.save
        format.html { redirect_to @roaster, notice: 'Roaster was successfully created.' }
        format.json { render :show, status: :created, location: @roaster }
      else
        format.html { render :new }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roasters/1
  # PATCH/PUT /roasters/1.json
  def update
    respond_to do |format|
      if @roaster.update(roaster_params)
        format.html { redirect_to @roaster, notice: 'Roaster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roaster }
      else
        format.html { render :edit }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roasters/1
  # DELETE /roasters/1.json
  def destroy
    @roaster.destroy
    respond_to do |format|
      format.html { redirect_to roasters_url, notice: 'Roaster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roaster
      @roaster = Roaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roaster_params
      params.require(:roaster).permit(:name, :location, :website)
    end
end

app/helpers/roasters_helper.rb
module RoastersHelper
    def roasters_list
        Roaster.all.map { |o| [o.name, o.id] }
    end

    def roaster_name id
        Roaster.all.find(id).name rescue "INVALID"
    end
end

app/views/roasters/_form.html.haml
= form_for @roaster do |f|
  - if @roaster.errors.any?
    #error_explanation
      %h2= "#{pluralize(@roaster.errors.count, "error")} prohibited this roaster from being saved:"
      %ul
        - @roaster.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :website
    = f.text_field :website
  .actions
    = f.submit 'Save'

app/views/roasters/edit.html.haml
%h1 Editing roaster

= render 'form'

= link_to 'Show', @roaster
\|
= link_to 'Back', roasters_path

app/views/roasters/index.html.haml
%h1 Roasters

%table.table
  %thead
    %tr
      %th Name
      %th Location
      %th Website
      %th
      %th

  %tbody
    - @roasters.each do |roaster|
      %tr
        %td= roaster.name
        %td= roaster.location
        %td= roaster.website
        %td= link_to 'Show', roaster
        %td= link_to 'Edit', edit_roaster_path(roaster)

%br

= link_to 'New Roaster', new_roaster_path

app/views/roasters/new.html.haml
%h1 New roaster

= render 'form'

= link_to 'Back', roasters_path

app/views/roasters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @roaster.name
%p
  %b Location:
  = @roaster.location
%p
  %b Website:
  = @roaster.website

= link_to 'Edit', edit_roaster_path(@roaster)
\|
= link_to 'Back', roasters_path