config/routes.rb
Rails.application.routes.draw do

  get "beans/current", to: "beans#current", as: :current_beans
  get "beans/cupping", to: "beans#cupping", as: :cupping_beans
  post "beans/:bean_id/rate", to: "beans#rate", as: :rate_bean
  post "beans/:bean_id/toggle_in_stock", to: "beans#toggle_in_stock", as: :bean_toggle_in_stock

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :beans
  resources :roasters
  resources :roast_levels
  resources :origins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "beans#current"

end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController
  before_action :set_origin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update]

  # GET /origins
  # GET /origins.json
  def index
    @origins = Origin.all
  end

  # GET /origins/1
  # GET /origins/1.json
  def show
  end

  # GET /origins/new
  def new
    @origin = Origin.new
  end

  # GET /origins/1/edit
  def edit
  end

  # POST /origins
  # POST /origins.json
  def create
    @origin = Origin.new(origin_params)

    respond_to do |format|
      if @origin.save
        format.html { redirect_to @origin, notice: 'Origin was successfully created.' }
        format.json { render :show, status: :created, location: @origin }
      else
        format.html { render :new }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /origins/1
  # PATCH/PUT /origins/1.json
  def update
    respond_to do |format|
      if @origin.update(origin_params)
        format.html { redirect_to @origin, notice: 'Origin was successfully updated.' }
        format.json { render :show, status: :ok, location: @origin }
      else
        format.html { render :edit }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /origins/1
  # DELETE /origins/1.json
  def destroy
    @origin.destroy
    respond_to do |format|
      format.html { redirect_to origins_url, notice: 'Origin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_origin
      @origin = Origin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def origin_params
      params.require(:origin).permit(:name)
    end
end

app/helpers/origins_helper.rb
module OriginsHelper
    def origins_list
        Origin.all.map { |o| [o.name, o.id] }
    end

    def origin_name id
        Origin.all.find(id).name rescue "INVALID"
    end


end

app/views/origins/_form.html.haml
= form_for @origin do |f|
  - if @origin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@origin.errors.count, "error")} prohibited this origin from being saved:"
      %ul
        - @origin.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/origins/edit.html.haml
%h1 Editing origin

= render 'form'

= link_to 'Show', @origin
\|
= link_to 'Back', origins_path

app/views/origins/index.html.haml
%h1 Origins

%table.table
  %thead
    %tr
      %th Name
      %th
      %th

  %tbody
    - @origins.each do |origin|
      %tr
        %td= origin.name
        %td= link_to 'Show', origin
        %td= link_to 'Edit', edit_origin_path(origin)

%br

= link_to 'New Origin', new_origin_path

app/views/origins/new.html.haml
%h1 New origin

= render 'form'

= link_to 'Back', origins_path

app/views/origins/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @origin.name

= link_to 'Edit', edit_origin_path(@origin)
\|
= link_to 'Back', origins_path