config/routes.rb
Rails.application.routes.draw do

  get "beans/current", to: "beans#current", as: :current_beans
  get "beans/cupping", to: "beans#cupping", as: :cupping_beans
  post "beans/:bean_id/rate", to: "beans#rate", as: :rate_bean
  post "beans/:bean_id/toggle_in_stock", to: "beans#toggle_in_stock", as: :bean_toggle_in_stock

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :beans
  resources :roasters
  resources :roast_levels
  resources :origins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "beans#current"

end

app/controllers/beans_controller.rb
class BeansController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :set_bean, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:rate, :create, :update]

  # GET /beans
  # GET /beans.json
  def index
    if (params[:sort] == "average_rating")
      @beans = Bean.sorted_by_average_rating
      if (sort_direction == "desc")
        @beans.reverse!
      end
    else
      @beans = Bean.order(sort_column + " " + sort_direction)
    end
  end

  def current
    @beans = Bean.all.where(in_stock: true)
  end

  def cupping
    @beans = Bean.all.where(cupping: true)
  end

  # GET /beans/1
  # GET /beans/1.json
  def show
  end

  # GET /beans/new
  def new
    @bean = Bean.new
  end

  # GET /beans/1/edit
  def edit
  end

  # POST /beans
  # POST /beans.json
  def create
    @bean = Bean.new(bean_params)

    respond_to do |format|
      if @bean.save
        format.html { redirect_to @bean, notice: 'Bean was successfully created.' }
        format.json { render :show, status: :created, location: @bean }
      else
        format.html { render :new }
        format.json { render json: @bean.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beans/1
  # PATCH/PUT /beans/1.json
  def update
    respond_to do |format|
      if @bean.update(bean_params)
        format.html { redirect_to @bean, notice: 'Bean was successfully updated.' }
        format.json { render :show, status: :ok, location: @bean }
      else
        format.html { render :edit }
        format.json { render json: @bean.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beans/1
  # DELETE /beans/1.json
  def destroy
    @bean.destroy
    respond_to do |format|
      format.html { redirect_to beans_url, notice: 'Bean was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def rate
    bean = Bean.all.find(params[:bean_id])
    if bean.cupping
      bean_rating = BeanRating.new(bean_id: params[:bean_id], rating: params[:rating])
      bean_rating.save
      binding.pry
      redirect_to cupping_beans_path
    else
      bean_rating = BeanRating.all.where(bean_id: params[:bean_id], user_id: current_user.id)[0]
      unless params[:rating].blank?
        if bean_rating
          bean_rating.update(rating: params[:rating])
        else
          bean_rating = BeanRating.new(bean_id: params[:bean_id], user_id: current_user.id, rating: params[:rating])
          bean_rating.save
        end
      end
      redirect_to current_beans_path
    end
  end

  def toggle_in_stock
    bean = Bean.find(params[:bean_id])
    if bean
      bean.update(in_stock: !bean.in_stock)
    end
    redirect_to current_beans_path
  end


  private
  
    def sort_column
      Bean.columns.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_bean
      @bean = Bean.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bean_params
      params.require(:bean).permit(:roaster_id, :name, :roast_level_id, :origin_id, :notes, :in_stock)
    end
end

app/helpers/beans_helper.rb
module BeansHelper

    def average_rating bean_id
        ratings = BeanRating.all.where(bean_id: bean_id).map { |b| b.rating }
        (ratings.inject { |sum, element| sum + element }.to_f / ratings.size).round(1)
    end

    def user_rating user, bean_id
        return nil unless user
        BeanRating.all.where(user_id: user.id, bean_id: bean_id)[0].rating rescue nil
    end

    def rating_distribution bean_id
        ratings = BeanRating.all.where(bean_id: bean_id)
        buckets = rating_buckets
        ratings.each { |r| buckets[r.rating - 1] += 1 }
        buckets
    end

    def bean_rating_options
        [
            ["5 - I would bathe in this", 5],
            ["4 - Good", 4],
            ["3 - Okay", 3],
            ["2 - I'll drink it, but I won't like it", 2],
            ["1 - This belongs in a toilet", 1]
        ]
    end

    private

    def rating_buckets
        [0,0,0,0,0]
    end

end

app/views/beans/_card.haml
-user_rate = user_rating(current_user, bean.id)
.row
  .col-sm-6
    %h2=bean.name
  .col-sm-6
    -if current_user
      =form_tag(bean_toggle_in_stock_path(bean_id: bean.id)) do
        =field_set_tag do
          -stock_string = "In Stock!"
          -stock_string = "No more :(" if bean.in_stock
          =submit_tag stock_string, class: 'btn btn-primary', data: { confirm: 'Are you sure?' }

%table.table
  %tbody
    %tr
      %td.strong Roaster
      %td= roaster_name bean.roaster_id
    %tr
      %td Roast Level
      %td= roast_level_name bean.roast_level_id
    %tr
      %td Origin
      %td= origin_name bean.origin_id
    %tr
      %td Notes
      %td= bean.notes
    %tr
      %td In Stock
      %td= bean.in_stock
    -if user_rate || show_avg
      %tr
        %td Average Rating
        %td= bean.average_rating
    -if current_user
      =form_tag(rate_bean_path(bean_id: bean.id)) do
        =field_set_tag do
          %tr
            %td Your Rating
            %td.form-inline
              = select_tag "rating", options_for_select(bean_rating_options, user_rating(current_user, bean.id)), include_blank: true, class: 'form-control short-select'
              = submit_tag "submit", class: 'btn btn-primary'

app/views/beans/_form.html.haml
= form_for @bean, class: 'form-group' do |f|
  - if @bean.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bean.errors.count, "error")} prohibited this bean from being saved:"
      %ul
        - @bean.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :roaster_id
    = f.select :roaster_id, options_for_select(roasters_list)
  .field
    = f.label :roast_level_id
    = f.select :roast_level_id, options_for_select(roast_levels_list)
  .field
    = f.label :origin_id
    = f.select :origin_id, options_for_select(origins_list)
  .field
    = f.label :notes
    = f.text_area :notes
  .field
    = f.label :in_stock
    = f.check_box :in_stock
  .actions
    = f.submit 'Save'

app/views/beans/cupping.haml
.container-fluid
  -@beans.each do |bean|
    .col-lg-4.col-md-6.col-sm-12
      .well=render 'card', bean: bean, show_avg: false

app/views/beans/current.haml
.container-fluid
  -@beans.each do |bean|
    .col-lg-4.col-md-6.col-sm-12
      .well=render 'card', bean: bean, show_avg: false

app/views/beans/edit.html.haml
%h1 Editing bean

= render 'form'

= link_to 'Show', @bean
\|
= link_to 'Back', beans_path

app/views/beans/index.html.haml
.container
  %h1 Bean History
  = link_to 'New Bean', new_bean_path, class: "btn btn-primary"
  %table.table
    %thead
      %tr
        %th=sortable "name"
        %th=sortable "roaster_id", "Roaster"
        %th=sortable "roast_level_id", "Roast level"
        %th=sortable "origin_id", "Origin"
        %th=sortable "notes"
        %th=sortable "in_stock"
        %th=sortable "average_rating"
        %th
        %th

    %tbody
      - @beans.each do |bean|
        %tr
          %td= bean.name
          %td= roaster_name bean.roaster_id
          %td= roast_level_name bean.roast_level_id
          %td= origin_name bean.origin_id
          %td= bean.notes
          %td= bean.in_stock
          %td= bean.average_rating
          %td= link_to 'Show', bean
          %td= link_to 'Edit', edit_bean_path(bean)

  %br

  = link_to 'New Bean', new_bean_path, class: "btn btn-primary"

app/views/beans/new.html.haml
%h1 New bean

= render 'form'

= link_to 'Back', beans_path

app/views/beans/show.html.haml
%p#notice= notice

.container
  .row
    .col-md-6.col-sm-12=render 'card', bean: @bean, show_avg: true

  -distribution = rating_distribution(@bean.id)
  .row
    .col-md-6.col-sm-12
      %b Ratings Breakdown
      %table.table.table-bordered
        %thead
          %tr
            -distribution.each_with_index do |_, index|
              %th=index + 1
        %tbody
          %tr
            -distribution.each do |votes|
              %td=votes