config/routes.rb
Rails.application.routes.draw do

  get "beans/current", to: "beans#current", as: :current_beans
  get "beans/cupping", to: "beans#cupping", as: :cupping_beans
  post "beans/:bean_id/rate", to: "beans#rate", as: :rate_bean
  post "beans/:bean_id/toggle_in_stock", to: "beans#toggle_in_stock", as: :bean_toggle_in_stock

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :beans
  resources :roasters
  resources :roast_levels
  resources :origins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "beans#current"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title beanSort
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "#"} beanSort
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              =link_to current_beans_path do
                Current Beans
            %li
              =link_to beans_path do
                Bean History
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Other stuff
                %span.caret
              %ul.dropdown-menu
                %li
                  =link_to roasters_path do
                    Roasters
                %li
                  =link_to origins_path do
                    Origins
                %li
                  =link_to roast_levels_path do
                    Roast Levels
          -# %form.navbar-form.navbar-left
          -#   .form-group
          -#     %input.form-control{:placeholder => "Search", :type => "text"}/
          -#   %button.btn.btn-default{:type => "submit"} Submit
          %ul.nav.navbar-nav.navbar-right
            -# %li
            -#   %a{:href => "#"} Link
            %li
              =link_to 'http://github.com/jusroberts/coffee-snobs' do
                Contribute
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                -if current_user
                  =current_user.email
                  %span.caret
                  %ul.dropdown-menu
                    %li
                      =link_to "Logout", destroy_user_session_path, method: :delete

                -else
                  Not Signed In
                  %span.caret
                  %ul.dropdown-menu
                    %li
                      =link_to new_user_session_path do
                        Login
          -#     %ul.dropdown-menu
          -#       %li
          -#         %a{:href => "#"} Action
          -#       %li
          -#         %a{:href => "#"} Another action
          -#       %li
          -#         %a{:href => "#"} Something else here
          -#       %li.divider{:role => "separator"}
          -#       %li
          -#         %a{:href => "#"} Separated link
    = yield